Downgrade url since into trait for iron url type has disappeared
error[E0277]: the trait bound `url::Url: std::convert::From<iron::Url>` is not satisfied
  --> src/http.rs:79:48
   |
79 |         let mut req_url: Url = req.url.clone().into();
   |                                                ^^^^ the trait `std::convert::From<iron::Url>` is not implemented for `url::Url`
   |
   = note: required because of the requirements on the impl of `std::convert::Into<url::Url>` for `iron::Url`